language: ruby
# dist: xenial #16.04
dist: bionic #18.04
sudo: required
rvm:
  - 2.7
env:
  global:
  - VAGRANT_VERSION="2.2.7"
before_install:
  - sudo apt-get -qq update
jobs:
  include:
    - stage: "build Vagrant and Libvirt with KVM QEMU"
      script:
          # - sudo apt-get install libvirt-bin libvirt-dev qemu-utils qemu
          # - sudo systemctl status libvirtd
          - sudo apt-get install -y cpu-checker bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
          - sudo libvirtd --version
          # - sudo apt-get install cpu-checker -y
          - sudo kvm-ok
          - egrep -c '(vmx|svm)' /proc/cpuinfo #If 0 it means that your CPU doesn't support hardware virtualization.If 1 or more it does - but you still need to make sure that virtualization is enabled in the BIOS.
          - sudo addgroup libvirtd
          - sudo adduser  $(id -un) libvirtd #ensure that your username is added to the group libvirtd
          # - sudo kvm-ok
          # - sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
          - sudo wget -nv https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
          - sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
          - vagrant version
          - sudo vagrant plugin install vagrant-libvirt
          - sudo vagrant plugin install vagrant-mutate
          - sudo vagrant status
          - sudo vagrant box add "bento/ubuntu-16.04" # does not support libvirt provider
          - sudo vagrant mutate "bento/ubuntu-16.04" libvirt # convert to libvirt provider
          - vagrant box list #verify installed boxes
          - vagrant status #Check the status of the VMs
          - sudo virsh list --all #show all running KVM/libvirt VMs
          - sudo vagrant up --provider=libvirt
          # - sudo vagrant up --provider=libvirt nomad-sandbox
          - sudo vagrant status
          - sudo vagrant global-status
          # - sudo vagrant ssh nomad-sandbox -c "nomad server members"
          # - nomad server members # view the members of the gossip ring
          # - nomad node status # see the registered nodes of the Nomad cluster
          # - nomad job init #Example job file written to example.nomad
          # - nomad job run example.nomad #register example job
          # - nomad status example # inspect the status of the job
          - sudo virsh list --all #show all running KVM/libvirt VMs
after_success:
    - stage: Finalize
      script: sudo vagrant destroy -f
notifications:
  #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
